[project]
name = "coreutils"

[env]
bin = "target/bin"
lib = "target/lib"
extern = "../../lib"

rustc = "rustc +nightly"
flags = "-L ./target/lib -O -C codegen-units=1 %{env.import}"
import = "--extern macros --extern prelude --extern"

[tasks]
test.script = ["maid build -q %{arg.1}", "./%{env.bin}/%{arg.1} %{arg.2}"]

clean.script = [
    "rm %{env.bin}/%{arg.1}",
    "mkdir -p %{env.bin}",
    "mkdir -p %{env.lib}",
]

[tasks.lib]
path = "target/lib"
script = [
    "%{env.rustc} --crate-type=lib %{env.extern}/macros.rs",
    "%{env.rustc} --crate-type=lib %{env.extern}/prelude.rs",
    "%{env.rustc} --crate-type=proc-macro %{env.extern}/entry.rs",
]

[tasks.build]
depends = ["clean", "lib"]
script = "%{env.rustc} %{env.flags} cmd/%{arg.1}.rs --cfg 'feature=\"start\"' -o %{env.bin}/%{arg.1}"

[tasks.core]
depends = ["lib"]
script = [
    "rm %{env.bin}/core",
    "%{env.rustc} %{env.flags} cmd/core.rs -o %{env.bin}/core",
    "./%{env.bin}/core %{arg.1}",
]
